apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels: { app: myapp }
spec:
  replicas: 3
  selector:
    matchLabels: { app: myapp }
  template:
    metadata:
      labels: { app: myapp }
    spec:
      securityContext:
        runAsUser: 10001
        runAsNonRoot: true
      containers:
      - name: web
        image: myapp:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: "Europe/Stockholm"
        readinessProbe:
          httpGet: { path: /healthz, port: 8080 }
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /healthz, port: 8080 }
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels: { app: myapp }
spec:
  selector: { app: myapp }
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: NodePort
